// Copies rhp 2's package build into vendor/rhp, which "@bezda/rhp" points to (astro.config.mjs) until rhp 2 is on npm.
// Build rhp first (npm run build in its repo), then: npm run sync-rhp [path to the rhp repo, ../rhp by default].
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

const repo = path.resolve(process.argv[2] ?? "../rhp");
const built = path.join(repo, "dist/index.js");
if (!fs.existsSync(built)) throw new Error(`No ${built}: run npm run build in ${repo} first.`);
const commit = execFileSync("git", ["-C", repo, "rev-parse", "--short", "HEAD"]).toString().trim();
const dirty = execFileSync("git", ["-C", repo, "status", "--porcelain", "src"]).toString().trim() ? " with local changes" : "";
const out = path.resolve("vendor/rhp/index.js");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, `// @bezda/rhp 2, built from bezda-team/rhp at ${commit}${dirty}. Generated by npm run sync-rhp: don't edit.\n` + fs.readFileSync(built, "utf8"));
console.log(`vendor/rhp/index.js: rhp ${commit}${dirty}, ${fs.statSync(out).size} B`);
